### ISSUE TITLE
Doesn't work with GRIII

### ISSUE THREAD

**Issue by ungutknut** [clyang/GRsync#1]
I know, this script is for the GRII. But I think it's supposed to work with the GRIII too (according to David Webers post: https://www.dpreview.com/forums/thread/4375292).

However it doesn't work for me.

Viewing the pictures via firefox on path 192.168.0.1/v1/photos/135RICOH/*.JPG works fine and the script seems to find the correct path. But eventually it fails to download and shuts down the camera.

https://pastebin.com/wByNQwc4

If I skip the lines 108-111 and replace the else in 112 with the if from 108 it just hangs on "downloading" forever.

I defined an existing PHOTO_DEST_DIR in the script and nothing else. I guess STARTDIR and STARTFILE is supposed to stay empty?

I'm running the script on Xubuntu 18.04 with python 2.7.15+
Any hints to make this work with the GRIII?

edit: I just checked if I have all the python modules installed that are needed. I have them.

**Comment by clyang** [comment]
Hi,
My GRII is still working perfectly. So I don't own a GRIII for testing at the moment.

Here is my suggestion: Can you try to replace the following line:
https://github.com/clyang/GRsync/blob/f99337f1c5563f7f84cd4fbb4561d934f313b009/GRsync.py#L74
to

    f = urllib2.urlopen(GR_HOST+photouri+'?size=full')

Please let me know if this fixes the issue. Thanks.

**Comment by ungutknut** [comment]
Thanks but this didn't help. Neither is it mandatory in the browser. The terminal output is exactly the same as before.
I guess I'll have to create a dpreview account and ask David Weber.

**Comment by clyang** [comment]
After viewing threads on DPREVIEW. It seems to be a simple fix. I'll try to fix it again.

**Comment by clyang** [comment]
@ungutknut 
Can you give the latest fix a try? Thanks

**Comment by ungutknut** [comment]
You're a genius! Now it works flawless for me. Thanks a lot.
