### ISSUE TITLE
About GR IIIx

### ISSUE THREAD

**Issue by DOLATENO** [clyang/GRsync#5]
Can anyone help to use this program for my GR IIIx ?
I tried to change these.

SUPPORT_DEVICE(line 23) → Added GR IIIx
DEVICE(line 24) →  change it's device's name to GR IIIx

**Comment by clyang** [comment]
Can you add the following code `before` line 36?

> print props

Save it, run the modified script and post the output so I can diagnose the issue.

**Comment by DOLATENO** [comment]
Statements must be separated by newlines or semicolons(36,19)
 print props    
    ^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

If I should run the code with connecting , pls tell me about it.

**Comment by DOLATENO** [comment]
I connected my GR IIIx
Your source device 'RICOH GR IIIx' is unknown or not supported!

And the debug tool suggests me like this,
----------------------------------------------------------------------------------------------------------------------------
 File "/Users/Myname/.pyenv/versions/3.10.0/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/Mynamei/.pyenv/versions/3.10.0/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Myname/Desktop/GRsync.py", line 173, in <module>
    model = getDeviceModel()
  File "/Users/Myname/Desktop/GRsync.py", line 39, in getDeviceModel
    print("Unable to fetch device props from device")
UnboundLocalError: local variable 'print' referenced before assignment
----------------------------------------------------------------------------------------------------------------------------

**Comment by johnmaguire** [comment]
@DOLATENO Try adding `RICOH GR IIIx` to `SUPPORT_DEVICES`, not just `GR IIIx`.

As for your most recent error, it seems like maybe you weren't connected to the device at the time.

**Comment by DOLATENO** [comment]
@JohnMaguire 
Thanks !
I tried and I finally done.
Sorry for late reply,
